Repository YAPP-Github/FitRun-Android, pull requests merged in 2025-07, with the labels that each got.

#14 [DOCS] Add CodeRabbit config file
  .coderabbit.yaml
Labels: documentation

#15 [DESIGN][FIRTRUN-20] :feature:splash 스크린 UI 수정
  core/design-system/src/main/kotlin/com/yapp/fitrun/core/designsystem/Color.kt
  core/design-system/src/main/res/drawable/img_logo.png
  core/design-system/src/main/res/drawable/logo_splash_text.xml
  core/design-system/src/main/res/font/pretendard_bold.otf
  core/design-system/src/main/res/font/pretendard_medium.otf
  core/design-system/src/main/res/font/pretendard_regular.otf
  core/design-system/src/main/res/font/pretendard_semi_bold.otf
  feature/splash/src/main/kotlin/com/yapp/fitrun/feature/splash/FitRunSplashScreen.kt
Labels: UI

#19 [FIX] Fix multi module to type-safe
  app/build.gradle.kts
  core/data/build.gradle.kts
  core/design-system/build.gradle.kts
  core/network/build.gradle.kts
  core/ui/build.gradle.kts
  feature/login/build.gradle.kts
  feature/main/build.gradle.kts
  feature/splash/build.gradle.kts
  feature/workthrough/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#20 [FIX] Rename :core:design-system to :core:designsystem
  app/build.gradle.kts
  build-logic/convention/src/main/kotlin/fitrun.android.feature.gradle.kts
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/yapp/fitrun/core/designsystem/Color.kt
  core/designsystem/src/main/kotlin/com/yapp/fitrun/core/designsystem/Font.kt
  core/designsystem/src/main/res/drawable/ic_launcher_background.xml
  core/designsystem/src/main/res/drawable/ic_launcher_foreground.xml
  core/designsystem/src/main/res/drawable/logo_splash_text.xml
  core/designsystem/src/main/res/font/pretendard_bold.otf
  core/designsystem/src/main/res/font/pretendard_medium.otf
  core/designsystem/src/main/res/font/pretendard_regular.otf
  core/designsystem/src/main/res/font/pretendard_semi_bold.otf
  core/designsystem/src/main/res/mipmap-anydpi/ic_launcher.xml
  core/designsystem/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  core/designsystem/src/main/res/values/colors.xml
  core/designsystem/src/main/res/values/strings.xml
  core/designsystem/src/main/res/values/themes.xml
  core/ui/build.gradle.kts
  feature/splash/src/main/kotlin/com/yapp/fitrun/feature/splash/FitRunSplashScreen.kt
  feature/workthrough/src/main/kotlin/com/yapp/fitrun/feature/workthrough/WorkThroughScreen.kt
  feature/workthrough/src/main/kotlin/com/yapp/fitrun/feature/workthrough/viewmodel/WorkThroughViewModel.kt
  settings.gradle.kts
Labels: bug

#37 [FEAT][FITRUN-152] 달리기 전 온보딩 UI: 목표 설정
  feature/running/src/main/kotlin/com/yapp/fitrun/feature/running/runningonboarding/RunningOnBoardingScreen.kt
  feature/running/src/main/kotlin/com/yapp/fitrun/feature/running/runningonboarding/viewmodel/RunningOnBoardingState.kt
Labels: UI

#38 [FEAT][FITRUN-159] GitHub CI 구축
  .github/workflows/android.yml
Labels: enhancement

#40 [FIX] Update android.yml
  .github/workflows/android.yml
Labels: bug

#43 [FIX] Update android.yml
  .github/workflows/android.yml
Labels: bug

#44 [FEAT][FITRUN-45] :feature:running 기록 리스트 UI 구현
  core/designsystem/src/main/res/drawable/dummy_map.png
  core/designsystem/src/main/res/drawable/ic_no_data.xml
  feature/record/src/main/java/com/yapp/fitrun/feature/record/RecordScreen.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/RecordNavigation.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/RecordScreen.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordSideEffect.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordState.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordViewModel.kt
  feature/running/src/main/kotlin/com/yapp/fitrun/feature/running/runningonboarding/RunningOnBoardingScreen.kt
Labels: UI

#45 [FIX][#2] ktlint, detekt 컨벤션에 맞게 수정
  core/data/src/main/kotlin/com/yapp/fitrun/core/data/mapper/Mapper.kt
  core/data/src/main/kotlin/com/yapp/fitrun/core/data/repository/GoalRepositoryImpl.kt
  core/domain/src/main/kotlin/com/yapp/fitrun/core/domain/entity/GoalEntity.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/GoalDataSourceImpl.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/DistanceGoalRequest.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/PaceGoalRequest.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/RunningPurposeRequest.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/TimeGoalRequest.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/WeeklyRunCountRequest.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/response/goal/GoalResponse.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/response/goal/RecommendPaceResponse.kt
  core/ui/src/main/kotlin/com/yapp/fitrun/core/ui/TopAppBar.kt
  feature/home/src/main/kotlin/com/yapp/fitrun/feature/home/HomeScreen.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/yapp/fitrun/feature/main/MainNavigator.kt
  feature/main/src/main/kotlin/com/yapp/fitrun/feature/main/component/MainNavHost.kt
  feature/setgoal/build.gradle.kts
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/SetGoalScreen.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/component/PaceSection.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/component/RunningCountSection.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/navigation/SetGoalNavigation.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalEffect.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalState.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalViewModel.kt
Labels: bug

#51 [FIX][FITRUN-152] :feature:running 온보딩 lottie 추가
  core/designsystem/src/main/assets/countdown.json
  core/designsystem/src/main/assets/running_onboarding_txt.json
  core/designsystem/src/main/assets/toast_set_goal_completed.json
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/com/yapp/fitrun/core/ui/NoRippleClickable.kt
  feature/running/src/main/kotlin/com/yapp/fitrun/feature/running/runningonboarding/RunningOnBoardingScreen.kt
  feature/running/src/main/kotlin/com/yapp/fitrun/feature/running/runningonboarding/viewmodel/RunningOnBoardingViewModel.kt
  feature/setgoal/src/main/assets/toast_set_goal_completed.json
Labels: UI

#53 [FIX][FITRUN-40] 목표 설정 API 붙이기
  core/data/src/main/kotlin/com/yapp/fitrun/core/data/repository/GoalRepositoryImpl.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/request/goal/WeeklyRunCountRequest.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/SetGoalScreen.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/component/PaceSection.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/component/RunningCountSection.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalEffect.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalSideEffect.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalState.kt
  feature/setgoal/src/main/java/com/yapp/fitrun/feature/setgoal/viewmodel/SetGoalViewModel.kt
Labels: API

#54 [FEAT][FITRUN-164] 지도 SDK 러닝 경로 path overlay 추가
  core/common/src/main/kotlin/com/yapp/fitrun/core/common/ConvertTimeToPace.kt
  core/common/src/main/kotlin/com/yapp/fitrun/core/common/FormatMillisToString.kt
  core/data/src/main/kotlin/com/yapp/fitrun/core/data/mapper/Mapper.kt
  core/domain/src/main/kotlin/com/yapp/fitrun/core/domain/entity/RecordDetailEntity.kt
  core/network/src/main/kotlin/com/yapp/fitrun/core/network/model/response/RecordDetailResponse.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/RecordDetailScreen.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordDetailState.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordDetailViewModel.kt
  feature/record/src/main/kotlin/com/yapp/fitrun/feature/record/viewmodel/RecordViewModel.kt
Labels: UI, API
